- .travis.yml
- src/terraform-v1/.textlintrc
- `make lint`と`make build`を毎回実施
- タグがつけられたらGitHub pagesへデプロイ
> Add .travis.yml

- src/terraform/docs/d/local_router.md
- src/terraform/docs/index.md
- src/terraform/docs/r/local_router.md
- src/terraform/mkdocs.yml
related: https://github.com/sacloud/terraform-provider-sakuracloud/pull/648
ローカルルータのドキュメントを追加
> Add sakuracloud_local_router resource/dataSource

- src/terraform/docs/guides/upgrade_to_v2.0.0.md
- src/terraform/docs/provider.md
- src/terraform/mkdocs.yml
terraform-provider-sakuracloud v2へのアップグレードガイド
> terraform / upgrade guide

- src/terraform-v1/docs/installation.md
> terraform-v1: Fix broken links

- src/terraform/docs/d/server.md
- src/terraform/docs/guides/upgrade_to_v2.0.0.md
- src/terraform/docs/r/server.md
> Follow sacloud/terraform-provider-sakuracloud#677

- src/terraform/docs/index.md
- src/terraform/docs/r/archive.md
- src/terraform/docs/r/archive_share.md
- src/terraform/mkdocs.yml
terraform-provider-sakuracloud v2.2.0リリース後にマージする。
> Terraform: add sakuracloud_archive features

- src/terraform/docs/r/server.md
> Terraform: Startup Script Parameters

- src/terraform/docs/guides/upgrade_to_v2.1.0.md
- src/terraform/docs/guides/upgrade_to_v2.2.0.md
- src/terraform/docs/guides/upgrade_to_v2.3.0.md
- src/terraform/docs/index.md
- src/terraform/mkdocs.yml
> Upgrade guide for 2.2 and 2.3

- src/terraform/docs/d/archive.md
- src/terraform/docs/d/esme.md
- src/terraform/docs/guides/upgrade_to_v2.5.0.md
- src/terraform/docs/index.md
- src/terraform/docs/r/esme.md
- src/terraform/mkdocs.yml
v2.5.0向けドキュメント
https://github.com/sacloud/terraform-provider-sakuracloud/blob/master/CHANGELOG.md
> terraform-provider-sakuracloud v2.5.0

- src/top/docs/index.md
- src/top/mkdocs.yml
> Added link to UsaCon docs

- src/top/mkdocs.yml
トップページのナビゲーションを修正する。
修正前:
修正後:
> Set navigation_depth to 1

- src/usacon/docs/index.md
Usaconドキュメントに`Usacloudとの違い`項を追加
> Usacon: minor update

- src/usacon/docs/index.md
ChromeウェブストアでのUsaConのページへのURLを追加
> Added chrome web store URL

- src/terraform/docs/d/database.md
- src/terraform/docs/r/database.md
> Terraform: added sakuracloud_database.parameters

- src/usacloud/docs/commands/global.md
- src/usacloud/docs/guides/basic_usage.md
closes #51 
`USACLOUD_PROFILE`環境変数について追記
> Usacloud: Added description for USACLOUD_PROFILE environment variables

- src/usacloud/docs/commands/update-self.md
- src/usacloud/docs/index.md
- src/usacloud/mkdocs.yml
#61 対応の一部
セルフアップデート(`update-self`)コマンド用のドキュメントを追加
> Added update-self subcommand

- src/usacloud/docs/commands/profile.md
> Update profile guide

- src/usacloud/docs/upgrade/v1_1_0.md
アップグレードガイドの更新(https://github.com/sacloud/usacloud/pull/806 の反映)
> Usacloud: upgrade guide

- src/terraform/docs/guides/upgrade_to_v2.7.0.md
- src/terraform/docs/index.md
- src/terraform/mkdocs.yml
closes #56 
from #75 
v2.7.0向けのアップグレードガイドの追加
> Terraform: upgrade guides for v2.7.0

- src/autoscaler/mkdocs.yml
> AutoScaler: fixed title

- src/top/docs/index.md
- src/top/mkdocs.yml
- プロダクトごとのドキュメントへのリンクをカテゴリー化
- いくつかのプロダクトへのリンクを追加
> Improve top page

- src/terraform/docs/d/archive.md
> Terraform: os_type

- src/autoscaler/docs/examples/horizontal-scale-clone-server-and-elb.md
- src/autoscaler/mkdocs.yml
> AutoScaler: Added examples - clone server

- src/terraform/mkdocs.yml
> Terraform: upgrade guide to v2.16

- src/autoscaler/docs/getting_started.md
> autoscaler: fixed broken link

- src/autoscaler/docs/configuration.md
- ファイルパスについての記載を追加
- ファイルパスの記載に合わせ表現を微調整
> AutoScaler: リファレンスの修正

- src/autoscaler/docs/configuration.md
- src/autoscaler/mkdocs.yml
from #122 
- resource -> parentへの書き換え
- name_or_resource_selectorなどの型を追加
> AutoScaler: コンフィギュレーション更新

- src/autoscaler/docs/upgrade/v0.5.md
- src/autoscaler/mkdocs.yml
from #122 
v0.5へのアップグレードガイドを追加
> AutoScaler: Added upgrade guide

- src/autoscaler/docs/upgrade/v0.5.md
> AutoScaler: upgrade guide

- src/terraform-v1/mkdocs.yml
> terraform-v1: mkdocs.ymlの古い書き方を修正

- src/autoscaler/docs/network.md
- src/autoscaler/mkdocs.yml
IPアドレスなどの算出方法 & ディスクの修正が使えない場合について
> AutoScaler: 水平スケール時のネットワークについて追記

- src/autoscaler/docs/configuration.md
- src/autoscaler/docs/examples/horizontal-scale-server-and-elb.md
- src/autoscaler/docs/examples/horizontal-scale-server-and-lb.md
> AutoScaler: 記載ミス修正、特殊タグ追記

- src/autoscaler/docs/configuration.md
- src/autoscaler/docs/examples/horizontal-scale-clone-server-and-elb.md
- src/autoscaler/docs/examples/horizontal-scale-server-and-elb.md
- src/autoscaler/docs/examples/horizontal-scale-server-and-elb_cloud-init.md
- src/autoscaler/docs/examples/horizontal-scale-server-and-lb.md
- src/autoscaler/docs/network.md
- サーバグループにserver_name_prefixを追加
> AutoScaler v0.7

- src/terraform/docs/d/archive.md
- src/terraform/docs/d/auto_scale.md
- src/terraform/docs/guides/upgrade_to_v2.17.0.md
- src/terraform/docs/index.md
- src/terraform/docs/provider.md
- src/terraform/docs/r/auto_scale.md
- src/terraform/mkdocs.yml
> terraform-provider-sakuracloud v2.17

- src/terraform/docs/guides/upgrade_to_v2.17.0.md
- src/terraform/docs/r/auto_scale.md
from: https://github.com/sacloud/terraform-provider-sakuracloud/pull/900
> Terraform: yamlencodeからjsonencodeへ変更

- src/autoscaler/mkdocs.yml
- src/prometheus/mkdocs.yml
- src/terraform/mkdocs.yml
- src/top/mkdocs.yml
- src/usacloud/mkdocs.yml
- src/usacon/mkdocs.yml
closes #108 
repo_urlが設定されているとeditボタンも表示されてしまうため一旦除去して対応する
> repo_urlの除去

- src/terraform/docs/r/archive.md
- src/terraform/docs/r/auto_backup.md
- src/terraform/docs/r/auto_scale.md
- src/terraform/docs/r/bridge.md
- src/terraform/docs/r/cdrom.md
- src/terraform/docs/r/database.md
- src/terraform/docs/r/database_read_replica.md
- src/terraform/docs/r/disk.md
- src/terraform/docs/r/dns.md
- src/terraform/docs/r/esme.md
- src/terraform/docs/r/gslb.md
- src/terraform/docs/r/internet.md
- src/terraform/docs/r/ipv4_ptr.md
- src/terraform/docs/r/load_balancer.md
- src/terraform/docs/r/local_router.md
- src/terraform/docs/r/mobile_gateway.md
- src/terraform/docs/r/nfs.md
- src/terraform/docs/r/note.md
- src/terraform/docs/r/packet_filter.md
- src/terraform/docs/r/packet_filter_rules.md
- src/terraform/docs/r/proxylb.md
- src/terraform/docs/r/proxylb_acme.md
- src/terraform/docs/r/server.md
- src/terraform/docs/r/sim.md
- src/terraform/docs/r/simple_monitor.md
- src/terraform/docs/r/ssh_key.md
- src/terraform/docs/r/subnet.md
- src/terraform/docs/r/switch.md
- src/terraform/docs/r/vpc_router.md
> Terraform: importについて追記

- src/autoscaler/docs/configuration.md
closes #162 #163
- name_formatの追加
- use_group_tagの追加
> sacloud/autoscaler v0.10

- src/terraform/docs/d/archive.md
> Terraform: os_type更新

- src/terraform/docs/r/proxylb.md
https://github.com/sacloud/terraform-provider-sakuracloud/pull/1189 を反映
> terraform: exampleでのデフォルト値をより汎用的な用途向けに修正

- src/usacloud/docs/installation/start_guide.md
> Usacloud: 見出し誤りの修正

- src/usacloud/docs/installation/start_guide.md
-  Removed unnecessary colon after "Fish" to maintain consistency with other sections.
-  Ensured uniform formatting across different shell instructions.
This change helps in maintaining a consistent style throughout the documentation, making it easier to read and follow.
> Improve consistency in shell completion documentation

- src/terraform/docs/r/apprun_application.md
- src/terraform/docs/r/cdrom.md
- src/terraform/docs/r/webaccel_acl.md
- src/terraform/mkdocs.yml
closes #208 
closes #233 
terraform-provider-sakuracloud v2.25.4 ~ v2.26.1の変更内容のうち未反映だったものを取り込み
> terraform-provider-sakuracloudの更新の反映

- src/terraform/docs/d/webaccel.md
- src/terraform/docs/r/webaccel.md
- src/terraform/docs/r/webaccel_activation.md
- src/terraform/mkdocs.yml
Fixes #240
以下に関する日本語のドキュメンテーションを追加します。
* resource_sakuracloud_webaccel
* resource_sakuracloud_webaccel_activation
* datasource_sakuracloud_webaccel (attribute reference のみ更新)
~~以下のイシューに関する差分を取り込むことを念頭に置いておりますので、当分draftとさせて頂きます。~~
~~https://github.com/sacloud/terraform-provider-sakuracloud/issues/1258~~
諸事情により、上記イシューに対応する作業に着手できていません。
つきましては、いったん既存の実装済みリソース分のみドキュメントに追加させていただきたいと存じます。
ドキュメントの更新です。
> ウェブアクセラレーター (resource_webaccel, webaccel_activation)を追加
